# Generated by Django 2.2.4 on 2019-09-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandAboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aut',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
