# Generated by Django 2.2.4 on 2019-09-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Board_element',
        ),
    ]
