# Generated by Django 2.2.5 on 2019-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_element_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_element',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
